#!/usr/bin/env python3
"""Create the Neon schemas and copy both Straiit SQLite databases into them.

The migration is intentionally separate from the runtime API. It performs one
transaction against a direct (non-pooled) Neon connection and rolls everything
back if schema creation, copying, or row-count verification fails.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any
from urllib.parse import urlparse


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CATALOGUE_DB = PROJECT_ROOT.parent / "back_end" / "product_importer" / "products.db"
DEFAULT_PORTAL_DB = Path(__file__).resolve().parent / "portal.db"

CATALOGUE_TABLES = (
    "source_files",
    "products",
    "product_variants",
    "product_images",
)

PORTAL_TABLES = (
    "organizations",
    "account_applications",
    "users",
    "sessions",
    "demand_requests",
    "request_status_history",
    "quotes",
    "password_reset_tokens",
    "email_outbox",
    "reservations",
)

BOOLEAN_COLUMNS = {
    ("catalogue", "product_images", "is_primary"),
}

POSTGRES_SCHEMA = r"""
CREATE SCHEMA IF NOT EXISTS catalogue;
CREATE SCHEMA IF NOT EXISTS portal;

CREATE TABLE IF NOT EXISTS catalogue.source_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path TEXT NOT NULL UNIQUE,
    filename TEXT NOT NULL,
    file_type TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    modified_at TIMESTAMPTZ NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    product_count BIGINT NOT NULL DEFAULT 0,
    warning TEXT
);

CREATE TABLE IF NOT EXISTS catalogue.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file_id BIGINT NOT NULL REFERENCES catalogue.source_files(id) ON DELETE CASCADE,
    source_location TEXT NOT NULL,
    source_key TEXT NOT NULL,
    brand TEXT,
    name TEXT,
    category TEXT,
    model TEXT,
    sku TEXT,
    barcode TEXT,
    description TEXT,
    color TEXT,
    size TEXT,
    gender TEXT,
    material TEXT,
    quantity DOUBLE PRECISION,
    wholesale_price DOUBLE PRECISION,
    retail_price DOUBLE PRECISION,
    currency TEXT,
    status TEXT,
    image_path TEXT,
    offer_type TEXT,
    origin TEXT,
    hs_code TEXT,
    grade TEXT,
    model_year TEXT,
    collection TEXT,
    frame_color TEXT,
    lens_color TEXT,
    color_code TEXT,
    material_code TEXT,
    frame_material TEXT,
    bridge_size TEXT,
    branch_size TEXT,
    uva_filter TEXT,
    fitting TEXT,
    release_code TEXT,
    phase TEXT,
    order_quantity DOUBLE PRECISION,
    exceeding_quantity DOUBLE PRECISION,
    total_retail_value DOUBLE PRECISION,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    raw_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_file_id, source_key)
);
CREATE INDEX IF NOT EXISTS idx_products_brand ON catalogue.products(brand);
CREATE INDEX IF NOT EXISTS idx_products_category ON catalogue.products(category);
CREATE INDEX IF NOT EXISTS idx_products_sku ON catalogue.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_barcode ON catalogue.products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_name ON catalogue.products(name);

CREATE TABLE IF NOT EXISTS catalogue.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES catalogue.products(id) ON DELETE CASCADE,
    size TEXT NOT NULL,
    quantity DOUBLE PRECISION,
    barcode TEXT,
    sku TEXT,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    UNIQUE(product_id, size)
);
CREATE INDEX IF NOT EXISTS idx_variants_product ON catalogue.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_variants_barcode ON catalogue.product_variants(barcode);

CREATE TABLE IF NOT EXISTS catalogue.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES catalogue.products(id) ON DELETE CASCADE,
    source_file_id BIGINT NOT NULL REFERENCES catalogue.source_files(id) ON DELETE CASCADE,
    image_path TEXT NOT NULL,
    mime_type TEXT,
    source_sheet TEXT,
    source_row BIGINT,
    source_page BIGINT,
    source_x DOUBLE PRECISION,
    source_y DOUBLE PRECISION,
    width DOUBLE PRECISION,
    height DOUBLE PRECISION,
    sha256 TEXT NOT NULL,
    sort_order BIGINT NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    match_method TEXT,
    UNIQUE(product_id, image_path)
);
CREATE INDEX IF NOT EXISTS idx_product_images_product ON catalogue.product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_source ON catalogue.product_images(source_file_id);
CREATE INDEX IF NOT EXISTS idx_product_images_hash ON catalogue.product_images(sha256);

CREATE OR REPLACE VIEW catalogue.website_products AS
SELECT p.id, p.brand, p.name, p.category, p.model, p.sku, p.barcode,
       p.description, p.color, p.size, p.gender, p.material, p.quantity,
       p.wholesale_price, p.retail_price, p.currency, p.status, p.image_path,
       p.offer_type, p.origin, p.hs_code, p.grade, p.model_year, p.collection,
       p.frame_color, p.lens_color, p.color_code, p.material_code,
       p.frame_material, p.bridge_size, p.branch_size, p.uva_filter, p.fitting,
       p.release_code, p.phase, p.order_quantity, p.exceeding_quantity,
       p.total_retail_value, s.filename AS source_file, p.source_location,
       p.attributes_json
FROM catalogue.products p
JOIN catalogue.source_files s ON s.id = p.source_file_id;

CREATE TABLE IF NOT EXISTS portal.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country TEXT NOT NULL,
    registration_number TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portal.account_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    registration_number TEXT,
    country TEXT NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ,
    review_note TEXT
);
CREATE INDEX IF NOT EXISTS idx_applications_email ON portal.account_applications(email);
CREATE INDEX IF NOT EXISTS idx_applications_status ON portal.account_applications(status);

CREATE TABLE IF NOT EXISTS portal.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES portal.organizations(id),
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    display_name TEXT,
    role TEXT NOT NULL DEFAULT 'buyer' CHECK(role IN ('buyer','operator')),
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS portal.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES portal.users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    csrf_token TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON portal.sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON portal.sessions(expires_at);

CREATE TABLE IF NOT EXISTS portal.demand_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference TEXT UNIQUE,
    organization_id BIGINT NOT NULL REFERENCES portal.organizations(id),
    created_by BIGINT NOT NULL REFERENCES portal.users(id),
    request_type TEXT NOT NULL CHECK(request_type IN ('stock','wanted')),
    product_id BIGINT,
    product_snapshot_json TEXT,
    brand TEXT,
    category TEXT,
    quantity DOUBLE PRECISION NOT NULL CHECK(quantity > 0),
    target_price DOUBLE PRECISION,
    currency TEXT,
    destination TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','reviewing','sourcing','quoted','accepted','closed','rejected')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_requests_organization ON portal.demand_requests(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_requests_status ON portal.demand_requests(status);

CREATE TABLE IF NOT EXISTS portal.request_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES portal.demand_requests(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    note TEXT,
    changed_by BIGINT REFERENCES portal.users(id),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS portal.quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES portal.demand_requests(id) ON DELETE CASCADE,
    amount DOUBLE PRECISION NOT NULL,
    currency TEXT NOT NULL,
    valid_until DATE,
    terms TEXT,
    status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','accepted','expired','withdrawn')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portal.password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES portal.users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_password_resets_expiry ON portal.password_reset_tokens(expires_at);

CREATE TABLE IF NOT EXISTS portal.email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    text_body TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','sending','sent','failed')),
    attempts BIGINT NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_email_outbox_status ON portal.email_outbox(status, created_at);

CREATE TABLE IF NOT EXISTS portal.reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES portal.demand_requests(id) ON DELETE CASCADE,
    quote_id BIGINT NOT NULL REFERENCES portal.quotes(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL REFERENCES portal.organizations(id),
    quantity DOUBLE PRECISION NOT NULL CHECK(quantity > 0),
    status TEXT NOT NULL DEFAULT 'held' CHECK(status IN ('held','confirmed','released','expired')),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reservations_product ON portal.reservations(product_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_reservations_request ON portal.reservations(request_id, created_at DESC);
"""


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create Neon catalogue/portal schemas and import both SQLite databases."
    )
    parser.add_argument(
        "--catalogue-db", type=Path, default=DEFAULT_CATALOGUE_DB,
        help=f"source catalogue SQLite database (default: {DEFAULT_CATALOGUE_DB})",
    )
    parser.add_argument(
        "--portal-db", type=Path, default=DEFAULT_PORTAL_DB,
        help=f"source portal SQLite database (default: {DEFAULT_PORTAL_DB})",
    )
    parser.add_argument(
        "--replace", action="store_true",
        help="drop and recreate only the catalogue and portal schemas before importing",
    )
    parser.add_argument(
        "--check-only", action="store_true",
        help="validate the SQLite sources and show row counts without connecting to Neon",
    )
    return parser.parse_args()


def open_sqlite(path: Path) -> sqlite3.Connection:
    resolved = path.expanduser().resolve()
    if not resolved.is_file():
        raise SystemExit(f"SQLite database not found: {resolved}")
    connection = sqlite3.connect(f"file:{resolved.as_posix()}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA query_only = ON")
    return connection


def table_columns(connection: sqlite3.Connection, table: str) -> list[str]:
    return [str(row[1]) for row in connection.execute(f'PRAGMA table_info("{table}")')]


def source_counts(
    connection: sqlite3.Connection, tables: Iterable[str], source_name: str
) -> dict[str, int]:
    available = {
        str(row[0])
        for row in connection.execute("SELECT name FROM sqlite_master WHERE type='table'")
    }
    missing = [table for table in tables if table not in available]
    if missing:
        raise SystemExit(f"{source_name} is missing required tables: {', '.join(missing)}")
    return {
        table: int(connection.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0])
        for table in tables
    }


def print_counts(label: str, counts: dict[str, int]) -> None:
    print(label)
    for table, count in counts.items():
        print(f"  {table}: {count:,}")


def postgres_driver():
    try:
        import psycopg
        from psycopg import sql
    except ImportError as error:
        raise SystemExit(
            'PostgreSQL driver missing. Run: python -m pip install "psycopg[binary]>=3.2,<4"'
        ) from error
    return psycopg, sql


def direct_database_url() -> str:
    value = os.environ.get("NEON_DIRECT_DATABASE_URL", "").strip()
    if not value:
        raise SystemExit(
            "NEON_DIRECT_DATABASE_URL is not set. Copy the direct connection string "
            "from Neon and set it in this terminal."
        )
    parsed = urlparse(value)
    if parsed.scheme not in {"postgres", "postgresql"} or not parsed.hostname:
        raise SystemExit("NEON_DIRECT_DATABASE_URL is not a valid PostgreSQL connection string.")
    if "-pooler" in parsed.hostname:
        raise SystemExit(
            "Use Neon's direct connection string for migrations, not the pooled hostname."
        )
    return value


def convert_value(schema: str, table: str, column: str, value: Any) -> Any:
    if (schema, table, column) in BOOLEAN_COLUMNS and value is not None:
        return bool(value)
    if table == "quotes" and column == "valid_until" and value == "":
        return None
    return value


def copy_table(
    sqlite_connection: sqlite3.Connection,
    postgres_cursor: Any,
    sql: Any,
    schema: str,
    table: str,
    batch_size: int = 1_000,
) -> int:
    columns = table_columns(sqlite_connection, table)
    if not columns:
        raise RuntimeError(f"No columns found for {schema}.{table}")
    copy_statement = sql.SQL("COPY {}.{} ({}) FROM STDIN").format(
        sql.Identifier(schema),
        sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(column) for column in columns),
    )
    source_cursor = sqlite_connection.execute(f'SELECT * FROM "{table}" ORDER BY id')
    copied = 0
    with postgres_cursor.copy(copy_statement) as destination:
        while rows := source_cursor.fetchmany(batch_size):
            for row in rows:
                destination.write_row(
                    tuple(
                        convert_value(schema, table, column, row[column])
                        for column in columns
                    )
                )
                copied += 1
    return copied


def reset_identity(postgres_cursor: Any, schema: str, table: str) -> None:
    relation = f'{schema}."{table}"'
    postgres_cursor.execute("SELECT pg_get_serial_sequence(%s, 'id')", (relation,))
    sequence = postgres_cursor.fetchone()[0]
    if not sequence:
        return
    postgres_cursor.execute(f'SELECT COALESCE(MAX(id), 0) FROM "{schema}"."{table}"')
    maximum = int(postgres_cursor.fetchone()[0])
    postgres_cursor.execute(
        "SELECT setval(%s::regclass, %s, %s)",
        (sequence, maximum if maximum else 1, bool(maximum)),
    )


def target_count(postgres_cursor: Any, schema: str, table: str) -> int:
    postgres_cursor.execute(f'SELECT COUNT(*) FROM "{schema}"."{table}"')
    return int(postgres_cursor.fetchone()[0])


def ensure_empty_targets(postgres_cursor: Any) -> None:
    populated: list[str] = []
    for schema, tables in (("catalogue", CATALOGUE_TABLES), ("portal", PORTAL_TABLES)):
        for table in tables:
            count = target_count(postgres_cursor, schema, table)
            if count:
                populated.append(f"{schema}.{table} ({count:,} rows)")
    if populated:
        details = "\n  ".join(populated)
        raise RuntimeError(
            "Neon already contains Straiit data. Nothing was changed. "
            "Use --replace only if you intend to discard it:\n  " + details
        )


def prepare_target(postgres_cursor: Any, replace: bool) -> None:
    if replace:
        print("Replacing the Neon catalogue and portal schemas...")
        postgres_cursor.execute("DROP SCHEMA IF EXISTS catalogue CASCADE")
        postgres_cursor.execute("DROP SCHEMA IF EXISTS portal CASCADE")
    postgres_cursor.execute(POSTGRES_SCHEMA)
    if not replace:
        ensure_empty_targets(postgres_cursor)


def migrate(args: argparse.Namespace) -> None:
    catalogue = open_sqlite(args.catalogue_db)
    portal = open_sqlite(args.portal_db)
    try:
        catalogue_counts = source_counts(catalogue, CATALOGUE_TABLES, "Catalogue database")
        portal_counts = source_counts(portal, PORTAL_TABLES, "Portal database")
        print_counts("Catalogue source:", catalogue_counts)
        print_counts("Portal source:", portal_counts)
        if args.check_only:
            print("Source validation complete; Neon was not changed.")
            return

        psycopg, sql = postgres_driver()
        url = direct_database_url()
        print("Connecting to Neon with the direct connection...")
        with psycopg.connect(url) as postgres:
            with postgres.cursor() as cursor:
                prepare_target(cursor, args.replace)
                for schema, source, tables, expected in (
                    ("catalogue", catalogue, CATALOGUE_TABLES, catalogue_counts),
                    ("portal", portal, PORTAL_TABLES, portal_counts),
                ):
                    print(f"Importing {schema}...")
                    for table in tables:
                        copied = copy_table(source, cursor, sql, schema, table)
                        if copied != expected[table]:
                            raise RuntimeError(
                                f"Copy count mismatch for {schema}.{table}: "
                                f"expected {expected[table]}, copied {copied}"
                            )
                        reset_identity(cursor, schema, table)
                        print(f"  {table}: {copied:,}")

                for schema, tables, expected in (
                    ("catalogue", CATALOGUE_TABLES, catalogue_counts),
                    ("portal", PORTAL_TABLES, portal_counts),
                ):
                    for table in tables:
                        actual = target_count(cursor, schema, table)
                        if actual != expected[table]:
                            raise RuntimeError(
                                f"Verification failed for {schema}.{table}: "
                                f"expected {expected[table]}, found {actual}"
                            )
            postgres.commit()
        print("Migration complete. Both Neon schemas were committed successfully.")
    finally:
        catalogue.close()
        portal.close()


def main() -> int:
    args = arguments()
    try:
        migrate(args)
    except (RuntimeError, sqlite3.Error) as error:
        print(f"Migration failed: {error}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("Migration cancelled; the Neon transaction was rolled back.", file=sys.stderr)
        return 130
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
